"""empty message

Revision ID: 259255df40ed
Revises: 7a07001cd08d
Create Date: 2024-10-05 02:50:51.581952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259255df40ed'
down_revision = '7a07001cd08d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planet', schema=None) as batch_op:
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planet', schema=None) as batch_op:
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
